dtsw4 <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE)
dtsw4$DateTime<-strptime(paste0(as.character(dtsw4$Date),' ', as.character(dtsw4$Time)), "%d/%m/%Y %H:%M:%S")
inicio<-which(dtsw4$DateTime==strptime("2007-02-01", "%Y-%m-%d"))
final<-which(dtsw4$DateTime==strptime("2007-02-02 23:59:00", "%Y-%m-%d %H:%M:%S"))
dtsw4_filter<-dtsw4[inicio:final,]
png(filename = 'Plot4.png', width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
plot(dtsw4_filter$DateTime, as.numeric(dtsw4_filter$Global_active_power),type='l',ylab ="Global Active Power (kilowatts)", xlab="")
plot(dtsw4_filter$DateTime, as.numeric(dtsw4_filter$Voltage),type='l',ylab ="Voltage", xlab="datetime")
plot(dtsw4_filter$DateTime, as.numeric(dtsw4_filter$Sub_metering_1),type='l',ylab ="Enery sub metering", xlab="")
lines(dtsw4_filter$DateTime, as.numeric(dtsw4_filter$Sub_metering_2),type='l', col = "red")
  lines(dtsw4_filter$DateTime, as.numeric(dtsw4_filter$Sub_metering_3),type='l', col = "blue")
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1),col=c("black","red","blue"))
plot(dtsw4_filter$DateTime, as.numeric(as.character(dtsw4_filter$Global_reactive_power)),type='l',ylab ="Global_reactive_power", xlab="datetime")
dev.off()
